export default [
  {
    associatedCards: [],
    associatedCardRefs: [],
    assets: [
      {
        gameAbsolutePath: 'http://dummy.local/set1/en_us/img/cards/01DE001.png',
        fullAbsolutePath: 'http://dummy.local/set1/en_us/img/cards/01DE001-full.png',
      },
    ],
    regions: ['Demacia'],
    regionRefs: ['Demacia'],
    attack: 3,
    cost: 4,
    health: 3,
    description: '<link=vocab.Allegiance><style=Vocab>Allegiance</style></link>: Grant other allies +1|+1.',
    descriptionRaw: 'Allegiance: Grant other allies +1|+1.',
    levelupDescription: '',
    levelupDescriptionRaw: '',
    flavorText:
      '"You must understand the weight of our banner. It flies for our king, our houses, our citizens. It is our unwavering belief in Demacia itself. Hold it high. Show them our pride." - Tianna Crownguard ',
    artistName: 'SIXMOREVODKA',
    name: 'Vanguard Bannerman',
    cardCode: '01DE001',
    keywords: [],
    keywordRefs: [],
    spellSpeed: '',
    spellSpeedRef: '',
    rarity: 'RARE',
    rarityRef: 'Rare',
    subtypes: ['ELITE'],
    supertype: '',
    type: 'Unit',
    collectible: true,
    set: 'Set1',
    formats: ['Eternal'],
    formatRefs: ['client_Formats_Eternal_name'],
  },
];
