name: Node.js CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26.x

      - name: Enable corepack
        shell: bash
        run: corepack enable

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable

      - name: Run unit tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:ci

      - name: Publish test report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/*.json'
          summary-delta-report: true
          tests-changed-report: true
          upload-artifact: true
          fetch-previous-results: true
          always-group-by: true
          use-suite-name: true
          update-comment: true
          flaky-report: true
          pull-request-report: true
          summary-report: true
          overwrite-comment: true          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
